version: "3.7"
services:
#Rabbitmq Service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - '5672:5672'
        - '8080:15672'
    volumes:
        - ./rabbitmq/lib:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 30s
      retries: 15
    networks:
      - msgbroker

#Cart Service
  cart_service:
    container_name: cart_service
    build: 
      context: ./SweetOrganic/CartService
    ports:
      - '3001:3000'
    volumes:
      - .:/code
    depends_on:
      rabbitmq:
        condition: service_healthy
      cart_mongodb:
        condition: service_healthy
    environment:
      FLASK_DEBUG: "true"
    env_file:
      - ./SweetOrganic/CartService/.env
    networks:
    - msgbroker
    - cart_database

#Mongodb Cart Service
  cart_mongodb:
    image: mongo
    container_name: cart_mongodb
    ports:
      - '27019:27017'
    networks:
      - cart_database
    healthcheck:
      test: ["CMD", "mongo", "-d", "admin", "-f", "ping"]
      interval: 2s
      timeout: 30s
      retries: 15
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: admin

#Payment Service
  payment_service:
    container_name: payment_service
    build: 
      context: ./SweetOrganic/PaiementService
    ports:
      - '3002:3000'
    volumes:
      - .:/code
    depends_on:
      rabbitmq:
        condition: service_healthy
      payment_mongodb:
        condition: service_healthy
    environment:
      FLASK_DEBUG: "true"
    env_file:
      - ./SweetOrganic/PaiementService/.env
    networks:
    - msgbroker
    - payment_database

#Mongodb Payment Service
  payment_mongodb:
    image: mongo
    container_name: payment_mongodb
    ports:
      - '27020:27017'
    networks:
      - payment_database
    healthcheck:
      test: ["CMD", "mongo", "-d", "admin", "-f", "ping"]
      interval: 2s
      timeout: 30s
      retries: 15
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: admin

#Réseaux
networks:
  msgbroker:
    driver: bridge
  cart_database:
    driver: bridge
  payment_database:
    driver: bridge