version: "3.7"
services:
#Rabbitmq Service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - '5672:5672'
        - '8080:15672'
    volumes:
        - ./rabbitmq/lib:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 30s
      retries: 15
    networks:
      - msgbroker

#Mongodb Service
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27019:27017'
    networks:
      - cart_database
    healthcheck:
      test: ["CMD", "mongo", "-d", "admin", "-f", "ping"]
      interval: 2s
      timeout: 30s
      retries: 15
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: admin

#Cart Service
  cart_service:
    container_name: cart_service
    build: 
      context: .
    ports:
      - '3001:3000'
    volumes:
      - .:/code
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      FLASK_DEBUG: "true"
    env_file:
      - .env
    networks:
    - msgbroker
    - cart_database

#Réseaux
networks:
  msgbroker:
    driver: bridge
  cart_database:
    driver: bridge