version: '3'

services:

  mongo_db_product:
    container_name: SO_MongoDB_Produit
    image: mongo:latest   
    restart: always
    volumes:
      - mongo_db:/data/db 
    ports:
      - 27026:27017
    
  app:
    container_name: SO_API_Produit
    build: .
    ports:
      - 3026:3000
    depends_on:
      - mongo_db_product
      - rabbitmq
    env_file:
      - .env

  rabbitmq:
    container_name: some-rabbit
    image: rabbitmq:3-management
    ports:
      - 15672:15672  # Management UI
      - 5672:5672    # AMQP port
    restart: always

volumes:
  mongo_db: {}
